### ISSUE TITLE
FileDataSet object has no attribute ReferencedRTPlanSequence

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#100]
This `elif` should check for existence of `ReferencedRTPlanSequence` to avoid crash.

https://github.com/cutright/DVH-Analytics/blob/993f5510dd8ebeacebda2238befa11c80055c007/dvha/models/dicom_tree_builder.py#L561-L564

**Comment by lharzee** [comment]
Hi 
I have one more question.
How do you correct this in your program?
I m a novice in python program?

Thanks

Ludovic

**Comment by cutright** [comment]
I think you're asking how to use the new branch with the potential fix? Check out this [page](https://devconnected.com/how-to-switch-branch-on-git/) for more information.  Doing the following in the terminal / command line should work:

**Make sure your project is up to date**
`$ git pull`

**View available branches**
```
$ git branch
* master
  v0.8.8dev
``` 

**Switch to the branch mentioned above**  
`$ git checkout v0.8.8dev`

Then when you launch DVHA it will use the `v0.8.8dev` code.  If this doesn't resolve your issue, I'll need some anonymized files that cause the error to be able to reproduce and diagnose on this end.  You'll also want to eventually switch back to master once `v0.8.8dev` gets merged into `master`.  I'll post on here when that happens.

**Comment by cutright** [comment]
@lharzee Any luck? If you're having difficulty, you could download a pre-release executable from [here](https://github.com/cutright/DVH-Analytics/releases/tag/v0.8.8-dev.1).

**Comment by cutright** [comment]
I've released v0.8.8.  You can either download an executable here: https://github.com/cutright/DVH-Analytics/releases/tag/v0.8.8

Or update from PyPI via `pip`:
`pip install --upgrade dvha`

Just make sure you have at least v0.8.8

**Comment by lharzee** [comment]
Hi Dan

I have tried your new version but that's not working correctly.
Sorry :-(
The software stays blocked with the Rt Struct.
I'm actually on holiday but when I go back to work, I try to anonymize one
patient to send it to you, if you are ok?[image: Capture.JPG]
Ludovic


Le mer. 4 nov. 2020 à 00:18, Dan Cutright <notifications@github.com> a
écrit :

**Comment by cutright** [comment]
Based on your comment [here](https://github.com/cutright/DVH-Analytics/commit/5116d07b438d3fd16d98f41bcda76f9addf28be0#commitcomment-44006102), I believe this specific issue is resolved.

Although, it led to another issue, coincidentally resolved [here](https://github.com/cutright/DVH-Analytics/issues/105).

Finally, the rabbit hole led us to [this feature request](https://github.com/cutright/DVH-Analytics/issues/106).
