### ISSUE TITLE
truncation of display with .exe version

### ISSUE THREAD

**Issue by TroyChicago** [cutright/DVH-Analytics#101]
Hi, for the .exe version, I am wondering if anyone had encountered the issue of a truncated display, without the ability to scroll up/down.
I run the .exe version on two different laptops and both presented different 'level of truncation' shown in attached jpg.
Cheers
![error with truncated screen display in exe version](https://user-images.githubusercontent.com/73600461/97463103-671aa200-190d-11eb-8335-5960617c9d24.jpg)

**Comment by cutright** [comment]
Looks like you are running two different exe versions of DVHA (I don't recall which version I fixed the background color).

I'll try to change that left panel to a scrollable window... hopefully a simple fix.  Otherwise, you'd need to adjust your monitor resolution (seems fairly low?)

**Comment by TroyChicago** [comment]
the screenshots were from both the executable version (downloaded from the
webpage), and the non-exe (run from pycharm) version.

**Comment by TroyChicago** [comment]
hi, here's another display issue. (latest version 8.7 of DVHa_app.py ).

**Comment by cutright** [comment]
Looks like maybe the pictures attached from your email posts are not coming through?

I poked around with `wx.lib.scrolledpanel.ScrolledPanel`, but it's not trivial to implement with the existing DVHA layout.  I still need to work out dynamic resizing of the `ScrolledPanel`, then I'll push an update.

**Comment by cutright** [comment]
@troychitown What is your resolution?

**Comment by TroyChicago** [comment]
Hi,  I had run it on older systems, with max resolutions of 1366x768 and
1920 x 1080.  (I should clarify that with a higher resolution system, this
would not be an issue.) Cheers.

**Comment by cutright** [comment]
I have a scrollable view setup, but it's not stable; sometimes I get segmentation faults.  I also have a few annoying aesthetic sizing issues.  If it's not critical to you, I'd rather just implement a minimum resolution requirement for DVHA.

<img width="1225" alt="Screen Shot 2020-11-02 at 12 04 34 PM" src="https://user-images.githubusercontent.com/4778878/97902718-96f9e900-1d03-11eb-98e8-ae9343a5e068.png">

**Comment by TroyChicago** [comment]
hi, i wud agree with you that a minimal resolution one might be a more
efficient solution. ONce again, thanks!!
