### ISSUE TITLE
High resolution DVH for small volume ROI

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#119]
DVHA v0.9.1 allows for high resolution DVH calculations.  In User Settings, you can specify a small volume threshold which will trigger a high resolution calculation.  You can also specify how many interpolated segments will be calculated in-between ROI planes.  This is all based on built-in features to [dicompyler-core](https://dicompyler-core.readthedocs.io/en/latest/dicompylercore.html#module-dicompylercore.dvhcalc).

<img width="569" alt="image" src="https://user-images.githubusercontent.com/4778878/101862003-00f18380-3b37-11eb-890c-747bbe870e1d.png">

**Comment by cutright** [comment]
@Kiragroh I think this is what you were looking for?

**Comment by Kiragroh** [comment]
Amazing. Thank you.

**Comment by cutright** [comment]
Let us know how it works?  I'm a little unsure of the high resolution interpolation factor.  I've only tested on 4mm dose grids, hopefully it doesn't matter.

@bastula Did I implement this correctly?

https://github.com/cutright/DVH-Analytics/blob/d8e0ab4e89529021eab7f837afda528cb1ee416f/dvha/db/dicom_parser.py#L457-L458

I allow users to specify a `dvh_high_resolution_factor` in `[4, 8, 16, 32]`

**Comment by Kiragroh** [comment]
Maybe my data is not compatible with these interpolation methods. I tried a few setting-combinations and the dvh calculation time rises but dvh stairs remain. CT-slice distance is 1mm and 1mm doseGrid.
Here a screenshot: 
![screenshot_490](https://user-images.githubusercontent.com/44711812/101981983-f76c3680-3c70-11eb-8656-8df0f5c7d426.png)

**Comment by cutright** [comment]
@bastula I wonder if Eclipse is also smoothing the DVH itself?

**Comment by Kiragroh** [comment]
This is a good thought. Because the dvh looks smooth in Eclipse and no long calculation is required.

**Comment by cutright** [comment]
Have you tried importing one of your plans using the Eclipse DVH, and then import again using the DVHA calculation?  I'd be curious how they look plotted on top of one another.

**Comment by Kiragroh** [comment]
Eclipse does not export DVH-Infos in DICOM-Format (in RP or RD like in some other TPS). I can export a DVH-csv file. That would represent the calculated DVH in Eclipse and will be smooth if I do it via ESAPI (the standard Eclipse-DVH-Export has a fixed Bin-Width that is mostly not enough for small structures).

**Comment by cutright** [comment]
Are you sure about that? :)

**Comment by cutright** [comment]
Maybe you mean the Eclipse API doesn't offer it?  I have it through the main GUI.

**Comment by Kiragroh** [comment]
I was sure till you asked.^^ I tried your suggestion and same result in DVHA. Furthermore, I checked the DICOMs again and could not find DVH-data.
In ESAPI you are free to choose a DVH resolution. In Eclipse15.1-GUI I cannot manipulate the DVH-Bin-Width before export. Or I misremember because I do not use this export anymore because the output is not well structured. It is better for post-processing to buil something with ESAPI in my opinion.

**Comment by bastula** [comment]
Hi Max,

Is it possible to get an anonymized copy of the dataset (no need for CT) so
I can look at why this is happening in dicompyler-core?

**Comment by Kiragroh** [comment]
No problem, I send the data via eMail to Dan this morning. @cutright: can you please forward my mail.

Thanks guys for taking interest in my use-case. :)

**Comment by bastula** [comment]
Could you try setting the bin width from 5 cGy to 1 cGy? Maybe the dose fall off is not being modeled by 5 cGy bins.

**Comment by cutright** [comment]
@bastula pointed out to me that your DVH bin width in DVHA is 5cGy.  Can you set to that to 1cGy and re perform your query?  It's just a display option, the full 1cGy DVHs are stored in the DB (if I remember correctly).

**Comment by Kiragroh** [comment]
I tried this before, after realizing my mistake after uploading the picture but no big difference

**Comment by cutright** [comment]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/4778878/101988110-62137700-3c5d-11eb-9d16-7ae02fdbcea0.png">

**Comment by cutright** [comment]
Blue: DVHA_v0.9.0 (no interpolation)
Yellow: DVHA_v0.9.1 with 2 segments between and high res factor of 8
Orange: Eclipse DVH

**Comment by Kiragroh** [comment]
![screenshot_492](https://user-images.githubusercontent.com/44711812/101988405-9efd5f00-3c99-11eb-9642-1bf8fe034312.png)

okay, I tried again and compared directly. Little changes are visible.

But the stairs become not smaller. Maybe it cannot become better without more structure information or smoothing of the dvh curve itself.

**Comment by cutright** [comment]
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/4778878/101988527-cd5e4880-3c5f-11eb-80f7-89569ef05cbd.png">

**Comment by cutright** [comment]
I think the Eclipse GUI does some spline fitting (or similar) to the DVH data.  I can't imagine their internal DVH has *that* many more points than what they export.  But I guess it's possible.

**Comment by Kiragroh** [comment]
There seems to be some Varian-BlackMagic happening^^ But I see the same for ESAPI-DVH-Exports to csv. All nice&smooth.
They have to do this with the same source data. Therefore it would be nice to see some metric that can give the user an idea of the certainty of this estimation

**Comment by cutright** [comment]
What's peculiar to me is that the number of steps in the DVHs I posted, don't change between v0.9.0 and v0.9.1.

**Comment by cutright** [comment]
Sorry, not a super clean way to view this, but the count heights are discretized if you scroll all the way over to the right.  Maybe there's a rounding issue somewhere in DVHA (or less likely dicompyler-core)?

```
DVHs																																																																																																																																																																																																																																																																																																																																																																																
																																																																																																																																																																																																																																																																																																																																																																																
MRN	Study Instance UID	ROI Name	ROI Type	Rx Dose	Volume	Min Dose	Mean Dose	Max Dose																																																																																																																																																																																																																																																																																																																																																																								
DVHA_v0.9.0	DVHA_v0.9.0	cochlea^ right	ORGAN	27	0.031	2.54	3.00016129	3.53																																																																																																																																																																																																																																																																																																																																																																								
Eclipse	Eclipse	cochlea^ right	ORGAN	27	0.024849393	2.49	3.00797778	3.64																																																																																																																																																																																																																																																																																																																																																																								
DVHA_v0.9.1-2-8	DVHA_v0.9.1-2-8	cochlea^ right	ORGAN	27	0.026860696	2.36	2.882114302	3.44																																																																																																																																																																																																																																																																																																																																																																								
																																																																																																																																																																																																																																																																																																																																																																																
MRN	Study Instance UID	ROI Name	Dose bins (cGy) ->	0.5	1.5	2.5	3.5	4.5	5.5	6.5	7.5	8.5	9.5	10.5	11.5	12.5	13.5	14.5	15.5	16.5	17.5	18.5	19.5	20.5	21.5	22.5	23.5	24.5	25.5	26.5	27.5	28.5	29.5	30.5	31.5	32.5	33.5	34.5	35.5	36.5	37.5	38.5	39.5	40.5	41.5	42.5	43.5	44.5	45.5	46.5	47.5	48.5	49.5	50.5	51.5	52.5	53.5	54.5	55.5	56.5	57.5	58.5	59.5	60.5	61.5	62.5	63.5	64.5	65.5	66.5	67.5	68.5	69.5	70.5	71.5	72.5	73.5	74.5	75.5	76.5	77.5	78.5	79.5	80.5	81.5	82.5	83.5	84.5	85.5	86.5	87.5	88.5	89.5	90.5	91.5	92.5	93.5	94.5	95.5	96.5	97.5	98.5	99.5	100.5	101.5	102.5	103.5	104.5	105.5	106.5	107.5	108.5	109.5	110.5	111.5	112.5	113.5	114.5	115.5	116.5	117.5	118.5	119.5	120.5	121.5	122.5	123.5	124.5	125.5	126.5	127.5	128.5	129.5	130.5	131.5	132.5	133.5	134.5	135.5	136.5	137.5	138.5	139.5	140.5	141.5	142.5	143.5	144.5	145.5	146.5	147.5	148.5	149.5	150.5	151.5	152.5	153.5	154.5	155.5	156.5	157.5	158.5	159.5	160.5	161.5	162.5	163.5	164.5	165.5	166.5	167.5	168.5	169.5	170.5	171.5	172.5	173.5	174.5	175.5	176.5	177.5	178.5	179.5	180.5	181.5	182.5	183.5	184.5	185.5	186.5	187.5	188.5	189.5	190.5	191.5	192.5	193.5	194.5	195.5	196.5	197.5	198.5	199.5	200.5	201.5	202.5	203.5	204.5	205.5	206.5	207.5	208.5	209.5	210.5	211.5	212.5	213.5	214.5	215.5	216.5	217.5	218.5	219.5	220.5	221.5	222.5	223.5	224.5	225.5	226.5	227.5	228.5	229.5	230.5	231.5	232.5	233.5	234.5	235.5	236.5	237.5	238.5	239.5	240.5	241.5	242.5	243.5	244.5	245.5	246.5	247.5	248.5	249.5	250.5	251.5	252.5	253.5	254.5	255.5	256.5	257.5	258.5	259.5	260.5	261.5	262.5	263.5	264.5	265.5	266.5	267.5	268.5	269.5	270.5	271.5	272.5	273.5	274.5	275.5	276.5	277.5	278.5	279.5	280.5	281.5	282.5	283.5	284.5	285.5	286.5	287.5	288.5	289.5	290.5	291.5	292.5	293.5	294.5	295.5	296.5	297.5	298.5	299.5	300.5	301.5	302.5	303.5	304.5	305.5	306.5	307.5	308.5	309.5	310.5	311.5	312.5	313.5	314.5	315.5	316.5	317.5	318.5	319.5	320.5	321.5	322.5	323.5	324.5	325.5	326.5	327.5	328.5	329.5	330.5	331.5	332.5	333.5	334.5	335.5	336.5	337.5	338.5	339.5	340.5	341.5	342.5	343.5	344.5	345.5	346.5	347.5	348.5	349.5	350.5	351.5	352.5	353.5	354.5	355.5	356.5	357.5	358.5	359.5	360.5	361.5	362.5	363.5	364.5
DVHA_v0.9.0	DVHA_v0.9.0	cochlea^ right		1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
Eclipse	Eclipse	cochlea^ right		1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.5	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
DVHA_v0.9.1-2-8	DVHA_v0.9.1-2-8	cochlea^ right		1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	1	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.666666667	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0.333333333	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0

```

**Comment by cutright** [comment]
I think this is the culprit:
https://github.com/cutright/DVH-Analytics/blob/11f36bf6cc537061195f1f5e584aab59deca7ed1/dvha/db/dicom_parser.py#L462

**Comment by cutright** [comment]
Got it! The previous post was definitely an issue. Here was the other problem:

https://github.com/cutright/DVH-Analytics/blob/11f36bf6cc537061195f1f5e584aab59deca7ed1/dvha/models/dvh.py#L88
I changed that to:
`current_dvh = np.array(dvh_split[i], dtype=np.float)`

<img width="906" alt="image" src="https://user-images.githubusercontent.com/4778878/101989441-eb2eac00-3c65-11eb-8db0-a63f78cb421e.png">

also, I think maybe the DVH string should be in engineering notation instead.

**Comment by Kiragroh** [comment]
nice. I am excited for 0.9.2. 

If you would consider implementing some smoothing-feature I would suggest some sort of toggle button. In this way, the user can use it for temporarily manipulating the current DVH view for some nice image exports but the source data would not be manipulated.

Smoothing in the import process is surely also a possibility when TPS-vendors are doing it too, but deciding the right smoothing method for the user is maybe not optimal for everyone. And implementing smoothing options is surely too much effort for special cases with small structures.

**Comment by cutright** [comment]
Oh man, look at this beautiful plot :)

Need to look into the shift of the dicompyler-core interpolation curve.

<img width="906" alt="image" src="https://user-images.githubusercontent.com/4778878/101990069-2cc15600-3c6a-11eb-83a6-c5408337d117.png">

**Comment by Kiragroh** [comment]
oh man. Perfect. No additional smoothing necessary

**Comment by cutright** [comment]
Boom!  I'll do a pull request over on `dicompyler-core` shortly.

This is only with a high resolution factor of 4, no interpolation between planes.

<img width="924" alt="image" src="https://user-images.githubusercontent.com/4778878/101995814-70c85100-3c92-11eb-9b45-5dd4b23fcf22.png">

**Comment by cutright** [comment]
`dicompyler-core` pull request posted [here](https://github.com/dicompyler/dicompyler-core/pull/192)
