### ISSUE TITLE
Pb installation

### ISSUE THREAD

**Issue by OlivOlivOliv** [cutright/DVH-Analytics#12]
Good morning, 

I fallowed all instructions, and unfortunaltey I am not able to start / or launch the app according to your instruction.
I am using python 3.7 (from anaconda). I installed all libs from setup.py, and then manually.
I have still this message on the Prompt.

  File "G:\code python\DVH-Analytics-master\dvha\main.py", line 786, in OnInit
    self.frame = DVHAMainFrame(None, wx.ID_ANY, "")
  File "G:\code python\DVH-Analytics-master\dvha\main.py", line 83, in __init__
    self.__add_notebook_frames()
  File "G:\code python\DVH-Analytics-master\dvha\main.py", line 258, in __add_notebook_frames
    self.plot = PlotStatDVH(self.notebook_tab['DVHs'], self.dvh, self.options)
  File "G:\code python\DVH-Analytics-master\dvha\models\plot.py", line 171, in __init__
    self.__add_plot_data()
  File "G:\code python\DVH-Analytics-master\dvha\models\plot.py", line 215, in __add_plot_data
    self.iqr = self.figure.varea('x', 'y1', 'y2', source=self.source['patch'], alpha=self.options.IQR_ALPHA,
AttributeError: 'Figure' object has no attribute 'varea'
OnInit returned false, exiting...

Could I have some help.

Thank you.
Oliv

**Comment by cutright** [comment]
Hi Oliv, do you have Bokeh 1.2?

Dan

**Comment by OlivOlivOliv** [comment]
Hey Dan, 

Yes I have. I was trying to reinstall it, but no change.

(base) PS C:\Windows\System32> pip install bokeh
Requirement already satisfied: bokeh in c:\programdata\anaconda3\lib\site-packages (1.0.4)
Requirement already satisfied: tornado>=4.3 in c:\programdata\anaconda3\lib\site-packages (from bokeh) (6.0.2)
Requirement already satisfied: PyYAML>=3.10 in c:\programdata\anaconda3\lib\site-packages (from bokeh) (5.1)
Requirement already satisfied: pillow>=4.0 in c:\programdata\anaconda3\lib\site-packages (from bokeh) (5.4.1)
Requirement already satisfied: numpy>=1.7.1 in c:\programdata\anaconda3\lib\site-packages (from bokeh) (1.16.2)
Requirement already satisfied: Jinja2>=2.7 in c:\programdata\anaconda3\lib\site-packages (from bokeh) (2.10)
Requirement already satisfied: python-dateutil>=2.1 in c:\programdata\anaconda3\lib\site-packages (from bokeh) (2.8.0)
Requirement already satisfied: packaging>=16.8 in c:\programdata\anaconda3\lib\site-packages (from bokeh) (19.0)
Requirement already satisfied: six>=1.5.2 in c:\programdata\anaconda3\lib\site-packages (from bokeh) (1.12.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from Jinja2>=2.7->bokeh) (1.1.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\programdata\anaconda3\lib\site-packages (from packaging>=16.8->bokeh) (2.3.1)
(base) PS C:\Windows\System32>
still the same message

(base) PS G:\code python\DVH-Analytics-master> python .\dvha_app.py
Traceback (most recent call last):
  File "G:\code python\DVH-Analytics-master\dvha\main.py", line 786, in OnInit
    self.frame = DVHAMainFrame(None, wx.ID_ANY, "")
  File "G:\code python\DVH-Analytics-master\dvha\main.py", line 83, in __init__
    self.__add_notebook_frames()
  File "G:\code python\DVH-Analytics-master\dvha\main.py", line 258, in __add_notebook_frames
    self.plot = PlotStatDVH(self.notebook_tab['DVHs'], self.dvh, self.options)
  File "G:\code python\DVH-Analytics-master\dvha\models\plot.py", line 171, in __init__
    self.__add_plot_data()
  File "G:\code python\DVH-Analytics-master\dvha\models\plot.py", line 215, in __add_plot_data
    self.iqr = self.figure.varea('x', 'y1', 'y2', source=self.source['patch'], alpha=self.options.IQR_ALPHA,
AttributeError: 'Figure' object has no attribute 'varea'
OnInit returned false, exiting…

So I don 't know how to manage it, Do you have some ideas ?
Thank you
Oliv

**Comment by cutright** [comment]
Based on your output above, it looks like you have Bokeh v1.0.4?  To upgrade, you need to add an upgrade flag:
`pip install bokeh --upgrade`

Bokeh added varea glyphs in [v1.2.0](https://bokeh.pydata.org/en/latest/docs/releases.html#stacked-areas-and-lines).  Let me know if this resolves your issue?  Hopefully it does.

It's also possible you have multiple versions installed... if the above didn't solve your issue, you could alter the start function in main.py as follows:
```
def start():
    from bokeh import __version__
    print("bokeh v%s" % __version__)
    app = MainApp(0)
    app.MainLoop()
```

Your terminal should output bokeh v1.2.0 after opening DVHA.

**Comment by OlivOlivOliv** [comment]
Thank you Dan,

It s perfect now !!!
I am really impressed, it s a really great job that you made on this app !! Congratulations.

Oliv

**Comment by cutright** [comment]
Great!  Thanks Oliv, stay in touch.  I'm eager to hear how this software works out in the wild.
