### ISSUE TITLE
Adding a SQL column to the GUI

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#120]
A request was made to add an already existing SQL column into the interface.  I figured I'd use this as an opportunity to document how to do that.  Most likely, all you need to do is edit `dvha.db.sql_columns`.

The categorical dictionary is in this format:
`categorical[<GUI_NAME>] = {var_name: <SQL_COLUMN>, table: <SQL_TABLE>}`

The numerical dictionary is in this format:
`numerical[<GUI_NAME>] =  {var_name: <SQL_COLUMN>, table: <SQL_TABLE>, units:<DISPLAYED_UNITS>}`

Note that `numerical_detailed` includes some variables, which is meant to remove cumbersome variables in `Plans` and `Beams`.  Adding numerical columns here will keep them out of the GUI, except when viewing table data (e.g., Data -> Show Beams) or querying in the Database Administrator.

**There's no guarantee this will display the data in the way you expect, so be sure to interrogate the data.**

**Comment by cutright** [comment]
@Kiragroh We're on a roll here!

**Comment by Kiragroh** [comment]
Good explanation. Works like a charm

**Comment by Kiragroh** [comment]
Hi Dan. Found one problem. I added fx_grp_beam_count before your recent Master-Branch-Update and saw that you added it too. Thanks.
The problem is when I Query in a way that the TotalBeamCount is constant for all plans I get no output for this Query in 'TimeSeries'. I am certain that you implemented some If-Statement in these cases, because it is not necessary to calculate Min,Max,Mean&Median for a not changing value. Can I bypass this somehow? I would not care if Min,Max,Mean&Median are the same.

**Comment by cutright** [comment]
It’s not constant if you have multiple plans on the same study instance uid
(as is my case with boosts). I wasn’t sure of the best way to handle that.
I think maybe what you want is the sum of that value over the study
instance uid? Or maybe average?

For the short term, you can add a customization around line 94 in
dvha.tools.stats.__map_data

I’ll probably do the same after some more thought.

The other issue is poor database design on my part, that variable exists
once per beam. So really this variable may need a special case. Maybe put
that data into a set first to remove duplicates.

Now that I think about it, if I get rid of these duplicates, then the “stat” values should all come
out making more sense

**Comment by cutright** [comment]
https://github.com/cutright/DVH-Analytics/blob/126f204a73adc8009a9d7a0769158d849abf9e6d/dvha/tools/stats.py#L84-L97

**Comment by Kiragroh** [comment]
![screenshot_498](https://user-images.githubusercontent.com/44711812/102098520-9fc3fb80-3e27-11eb-8c49-a2966720be45.png)

Thanks for the help. I solved it not elegant but it works fine for the moment.
