### ISSUE TITLE
Small screen compatibility

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#123]
I've received some screenshots from multiple users illustrating inaccessible portions of the application when using a smaller screen (13" and smaller).  Sometimes missing toolbars or (`wx.Notebook`) tabs.

A related issue, the "Summary" in the bottom left should be put into a panel so that the text doesn't bleed over with smaller window dimensions.

**Comment by cutright** [comment]
@kiragroh Do you mind giving the latest `v0.9.2` branch a spin on your smaller screen? You *might* have to remove `.options` and `.options_checksum` in `~/Apps/dvh_analytics/preferences` if a bad window size was saved in your preferences.

**Comment by Kiragroh** [comment]
No problem. Will do it tomorrow and give you an update.
BTW: thx for the QueryFix. Should be working fine

**Comment by cutright** [comment]
Thanks Max,

Did you have Big Sur before?  I think Catalina right?  There might be some differences, but this is the only mildly relevant one I've found so far: [Re: macOS "Big Sur" and frame height](https://forums.wxwidgets.org/viewtopic.php?f=23&t=47709&sid=516fc407512277d7e914cceaf3c17577#p203031)

Did you delete `.options` and `.options_checksum`?

If you change the resolution here:
https://github.com/cutright/DVH-Analytics/blob/71e1e3593c259a3377e6f731ee8514c8feaa9b22/dvha/options.py#L273

Does anything change?  Do you mind seeing how small you need to make the resolution to work?

Linking [this](https://github.com/cutright/DVH-Analytics/issues/125#issuecomment-753450785) comment in this thread.

> Hi Dan, I tried the newest 0.9.2 branch.
> I can do anything on my 13'' MacBookPro (BigSur) because the buttons that are cutOff can be access via ContextBar. But Keyboard-Shortcut for Fullscreen (Command+Control+F) or other tricks to get Fullscreen is not working.
> 
> <img alt="screenshot_70" width="1440" src="https://user-images.githubusercontent.com/44711812/103454352-5eff2a00-4ce3-11eb-86a0-2f3b37970b09.png">

**Comment by Kiragroh** [comment]
You are right. I had Catalina before and I forgot to delte .options

With 600,400 it looks like that:
<img width="1440" alt="screenshot_72" src="https://user-images.githubusercontent.com/44711812/103462079-19fae800-4d23-11eb-946a-e2993c195ef8.png">

With 1300, 800 it looks like this:
<img width="1440" alt="screenshot_74" src="https://user-images.githubusercontent.com/44711812/103462087-30a13f00-4d23-11eb-915b-9c778338dde8.png">

Two suggestions:
a) maybe you could use screensize.height-100 and screensize.width-100 (there are some options for every OS: https://www.blog.pythonlibrary.org/2015/08/18/getting-your-screen-resolution-with-python/
b) attach the frame to the bottom of the screen. In this way, the user has the possibility to activate fullscreen

**Comment by Kiragroh** [comment]
Forgot two things:
a) the DVHA-Logo above 'Welcome to DVH Analytics.' is only showing up after manual resizing the window
b) the new screen size after manual resizing will not be saved for the next program start. I closed with red X

**Comment by cutright** [comment]
I have a variation of method a) here:

https://github.com/cutright/DVH-Analytics/blob/c7717216f709c2fdb2c19f859666216fdbe14ea5/dvha/tools/utilities.py#L683-L694

But I took it out while troubleshooting.

> Two suggestions:
> a) maybe you could use screensize.height-100 and screensize.width-100 (there are some options for every OS: https://www.blog.pythonlibrary.org/2015/08/18/getting-your-screen-resolution-with-python/
> b) attach the frame to the bottom of the screen. In this way, the user has the possibility to activate fullscreen

I don't currently have methods to save window sizes (only positions of some windows).

I have no idea what's going on with the missing logo.  

I've set the min resolution to (1200, 700) with a few more layout tweaks, and turned the relative sizing back on with a lower limit of of the min resolution.  Hopefully this latest commit fixes everything with probably the exception of the logo issue?

**Comment by Kiragroh** [comment]
https://github.com/cutright/DVH-Analytics/blob/d7d933e63ae7f998422eee5349504c0b9ea7f9f1/dvha/main.py#L791-L798

This is a good solution. 

The Logo issue is strange. When I toggle between 'Welcome' and 'DVH' it reappears too.

**Comment by cutright** [comment]
I'm still at a loss for the missing logo.  Is this with Big Sur?  I'm able to get my logo to "disappear" if the main window isn't wide enough, but that's much more narrow than your screen shot.  It may have to do with the text box size of the welcome message not being dynamic.

I think the latest 0.9.2 is good to go, with respect to window sizes, unfortunately, I'll have to push to master and make executables for my other users with screen size issues to test it out.

**Comment by Kiragroh** [comment]
no problem with mojave. strange

**Comment by cutright** [comment]
I'll take note of the logo issue, but I think small screen compatibility is good to go.
