### ISSUE TITLE
Unable to import any DICOM files (InvalidDicomError: File is missing DICOM File Meta Information)

### ISSUE THREAD

**Issue by DVHmonkey** [cutright/DVH-Analytics#15]
Hi, thanks for the work on the project. I am unable to import any DICOM files, and any assistance would be appreciated.

MS Windows 7 Pro 64-bit SP1 with admin privileges
All DVHA dependencies installed by pip in Python 3.7 via Spyder and/or Anaconda, verified with pip list
PostGreSQL 11.0-1 +pgAdmin 4 for SQL server

After running DVH analytics from Spider, I set up the SQL server and then attempted to import a DICOM set (CT, RTDOSE, RTPLAN, RTCONSTRUCT) of one of our patients as a test, but DVHA seems to be unable to detect any DICOM files. I verified the DICOM files by opening them with various DICOM viewers.

From a previous issue thread back in May it seems that it's pretty difficult importing files in a Windows environment, might this be the issue here as well?

Thanks and regards.

**Comment by cutright** [comment]
I don't believe it is a Windows issue in general.  I have it installed on work computer with MS Windows 7 (without admin privileges), as does a colleague of mine at a different institution.

Can you provide any output from your terminal?

**Comment by DVHmonkey** [comment]
Hi, thanks for your response. Will take some time to get terminal output as I am new to python and the aforementioned workstation is without internet access.

More details:
1. At the start screen for DVHA, I click 'Import", then "Browse", navigate to folder with DICOMs and "Select Folder".
2. A window with "Reading DICOM Headers" appears, and goes through the files, but once progress completes, the windows closes, I am returned to the "Import DICOM" window, with no studies identified and 0 plans parsed.
Something else I noticed is that after I attempt importing, pgAdmin4 shows the schema listing tables such as beams, dicom_files, dvhs, plans and rxs.

Will work on getting terminal output.

**Comment by ThirumuruganE** [comment]
Hi, I am new to python and as well as dvh analytics. I am getting the same issue. I am unable to import. I am using Ubuntu 18.04. Kindly help me to import Dicom.

**Comment by cutright** [comment]
@DVHmonkey Try the following code in a python console.  What is printed?
```
import pydicom
ds = pydicom.read_file('any_dicom_file_path')
print(ds.Modality)
```
It might also be worth downloading [Dicompyler]( https://www.dicompyler.com) to see if your files work there since I'm using similar methods.  Which treatment planning system are they from?  

With respect to pgAdmin, that's a good a sign.  DVHA creates those tables before you import anything, so that's normal and shows it can communicate to your SQL server.

@ThirumuruganE Can you elaborate?

**Comment by ThirumuruganE** [comment]
I tried import pydicom and read the file. I got error 21 and says it is a directory. kindly help me to solve this error. 
![Screenshot from 2019-12-09 22-45-13](https://user-images.githubusercontent.com/26036836/70457294-eb85eb80-1ad5-11ea-95ed-a0a4057ffe2a.png)

**Comment by cutright** [comment]
And you provided the dicom file path, not a directory?

**Comment by ThirumuruganE** [comment]
Sorry, it was a directory. right now I gave a file path and it returns an error. I am attaching screenshots for your perusal. and also in the sample folder, I have all CT images RT plan, RT Dose, RT structure set. I am also attaching that screenshot. I tried to import the whole DCM files by giving its path but I
![Screenshot from 2019-12-09 23-06-23](https://user-images.githubusercontent.com/26036836/70460146-a8c71200-1adb-11ea-971d-80d13ec91c02.png)
 am unable to do and it says it is directory 
![Screenshot from 2019-12-09 23-20-14](https://user-images.githubusercontent.com/26036836/70459894-28a0ac80-1adb-11ea-8d56-f7401e49f1a8.png)

**Comment by cutright** [comment]
Which planning system are you using?

Did you try this?
`ds = pydicom.read_file('dicom_file_path', force=True)`

**Comment by ThirumuruganE** [comment]
Now it is possible to import using `ds = pydicom.read_file('dicom_file_path', force=True)` . I am using Monaco TPS. kindly guide me with the steps I need to follow to import my plan in DVHA.
![Screenshot from 2019-12-09 23-40-21](https://user-images.githubusercontent.com/26036836/70461254-428fbe80-1ade-11ea-81c9-97b5e1876b3d.png)

**Comment by cutright** [comment]
OK, that's good news.  I will add an option to turn on the force import.  Since I don't understand the issue, I don't want to make that a default.  I should be able to take care of this after clinic hours tonight.

Which version of Monaco?  I haven't tried Monaco in a couple of years.

**Comment by ThirumuruganE** [comment]
Thank you!
I am currently using Monaco TPS version 5.1

**Comment by bastula** [comment]
I think it's fine to set force=true as a default unless you have corrupted DICOM files. I did that for dicompyler and dicompyler-core.

**Comment by cutright** [comment]
Awesome, thanks @bastula!

@ThirumuruganE Try using the latest Master now.  There might be other instances that use pydicom.read_file(), but they don't come to mind at the moment.

Added force=True to dvha/db/dicom_importer.py with commit https://github.com/cutright/DVH-Analytics/commit/0cd951c7a288a34bdc3ed0e6dde01812ceabcd03 and dvha/db/dicom_parser.py https://github.com/cutright/DVH-Analytics/commit/aab6dba2ec77dda07824d1f7815d892151e570a0
https://github.com/cutright/DVH-Analytics/blob/0cd951c7a288a34bdc3ed0e6dde01812ceabcd03/dvha/db/dicom_importer.py#L426

https://github.com/cutright/DVH-Analytics/blob/aab6dba2ec77dda07824d1f7815d892151e570a0/dvha/db/dicom_parser.py#L58-L71

**Comment by DVHmonkey** [comment]
Thanks for the replies. Using the latest master, the test patient's DICOM files were detected and parsed. Looking forward to using the program on a larger sample size. The original files were deleted after importing though.

Our planning software is Xio by Elekta.

For reference, this was the pydicom output:
In [2] was with Force=True
In [3] was without

![pydicom output](https://user-images.githubusercontent.com/58673531/70482121-01240100-1b28-11ea-98e7-cff263402414.jpg)

**Comment by bastula** [comment]
Yes XiO doesn't write a proper DICOM preamble so force=true is required for that TPS. Glad you could solve your issue!

**Comment by DVHmonkey** [comment]
Thanks for the help, everyone. Glad to have got it working. Now I have to figure out why I can't get it to see the ROIs, CTV, PTV, etc from the RT plan/dose/struct.

One last question: I was forced to use a Windows PC with admin privileges to run DVHA because I needed admin rights to install PostgreSQL (with the Windows installer), but it seems like some people are able to bypass that. Would this involve the binaries, or is there a much simpler way?

**Comment by cutright** [comment]
@DVHmonkey I have access to a SQL server running elsewhere.  I believe you do need admin privileges because of SQL.  I've thought about adding SQLite support to get around that, but I haven't had time to investigate.

I'm currently working on compiling DVHA into an executable/application, if I can get that to work I'll focus on packaging Postgres or maybe SQLite.

It sounds like this issue has been resolved (although new ones pending?).  I'm going to close this issue, but please create a new one if needed.
