### ISSUE TITLE
Slow Performance when using ROI MAP

### ISSUE THREAD

**Issue by bozhikovstanislav** [cutright/DVH-Analytics#151]
If more plans are inported.
The ROI MAP become not responsive . or too slow .

**Comment by cutright** [comment]
Can you be more specific?  On the import screen?

**Comment by bozhikovstanislav** [comment]
After I import all plans they are may be 2600 I do not know ..... 
The I try to use the menu from thr menu bar. ... 
it seams too much data to proces ..

**Comment by cutright** [comment]
Is it better after relaunching the application? Perhaps the import screen didn't release the memory it used.

**Comment by bozhikovstanislav** [comment]
When I add new Institutional ROI - It freezess . with Not Responding - and after about 1 or 2 minutes - the results is refreshed and done

**Comment by cutright** [comment]
I'm really unclear of the situation, can you provide some screenshots?

It sounds like you did a blind import of everything, and now you're editing the ROI Map after the import?

**Comment by cutright** [comment]
If my hunch in the last message is correct, the slow down is in the code below.

It's definitely not efficient.  My guess is that updating one ROI at a time is biggest contributor.

https://github.com/cutright/DVH-Analytics/blob/fdd100f6f02102838ad611cc48140a487ba28102/dvha/models/roi_map.py#L1226-L1455

**Comment by bozhikovstanislav** [comment]
Yes that it is what I did :)

**Comment by bozhikovstanislav** [comment]
I do not need ROI at that moment . I need Plans and WHat I do is to make Plan Catalog for ML . I have Data Base another DVHdatabase and also measurments results of the plans ... I do not have the plan geometries .. Now I have this also .... :)

**Comment by cutright** [comment]
It seems we have very similar interests.  Unfortunately (Fortunately?), development of the next evolution of DVH Analytics is taking up most of my time.  I'll try to do some research to see if I can speed this up given the architecture constraints.

In the mean time, if you do need the ROI map and if you're code savvy, it might be quicker (or at least less clicking and waiting in the GUI) to manually edit the (.roi file in `~/Apps/dvh_analytics/preferences`) and then Remap the entire database.  Note that this is physician dependent too, so maybe best to set all of your plans to the same physician.

`"<institutional_roi>":"<physician_roi>":"<variation_1>","<variation_2>","<variation_3>"`

For example:
```
"brainstem":"brainstem":"brainstem","brain stem","study brain stem"
"bronchus large":"bronchus large":"bronchus large"
"bronchus smaller airways":"bronchus smaller airways":"bronchus smaller airways"
"cauda equina":"cauda equina":"cauda equina"
```

**Comment by bozhikovstanislav** [comment]
Yes I will plan to do this.

I was wondering if it is posible to get the dose Map for the ISODOSE . as a Structure - AND then to map this with real one. .

I Have some knowlage on python. and C# and database .. Actualy the work flow here im my center of the physicist is design for colecting data .... ... 
I use on ML Model to predict gamma Pass of any plan that we created ... 
actualy it is very good ... 

Thank you for you help it is realy helpful to speed up the catalog :)

**Comment by cutright** [comment]
With the above commit, I only observed a ~5% speed improvement by updating all columns at once per row (with 70 rows in the DVHs table).

Updating multiple rows at once appears to be fairly complicated and I'm wary of creating temporary tables. Ultimately, the slowness is due to poor SQL design on my part.

I'm happy to accept a pull request if someone else sees a fix, but I don't see a good solution.

**Comment by bozhikovstanislav** [comment]
I can try to fix the designe of the SQL . this mean that the sql quearyes also must be fixed ... I can give it a try :)
