### ISSUE TITLE
Problem when trying to import DICOMs (AttributeError: 'Dataset' object has no attribute 'TransferSyntaxUID')

### ISSUE THREAD

**Issue by DVHmonkey** [cutright/DVH-Analytics#16]
Hi. As a follow-up to a previous issue, DVHA can parse the patient plans, however it is still unable to import patient plans, as documented below

Windows 7 Pro 64bit SP1, PostgresQL 11.0-1, pgAdmin4
DVHA launched with all dependencies, from Spyder 3.3.6 (Python 3.7) via Anaconda
DICOM files were obtained from Xio by Elekta

1. Import -> Point to folder with target DICOMs
![1](https://user-images.githubusercontent.com/58673531/70487667-70eeb780-1b39-11ea-9683-66046eb2599b.jpg)

2. Ticked checkbox next to 'Patients' -> All ROIs are red with X
![2](https://user-images.githubusercontent.com/58673531/70487701-8cf25900-1b39-11ea-9ffa-78284d22da2f.jpg)

3. Click and opened 'ROI Manager' and 'Dismiss'ed it immediately -> Some ROIs turned Green check
-> Also checked 'Import uncategorized ROIs'
![3](https://user-images.githubusercontent.com/58673531/70487750-bf03bb00-1b39-11ea-9c7e-f901163a1683.jpg)

4. After clicking 'Import', DVHA crashes with the following screen and terminal output.
![5](https://user-images.githubusercontent.com/58673531/70487819-ed819600-1b39-11ea-8a7b-89b08c9cf484.jpg)
![4](https://user-images.githubusercontent.com/58673531/70487823-f1151d00-1b39-11ea-80e4-b915a678a045.jpg)

5. Restarting DVHA and clicking 'Import' again.
![6](https://user-images.githubusercontent.com/58673531/70487865-0d18be80-1b3a-11ea-90f1-4c57c43abb18.jpg)

Attempting to repeat the process now results in the same results - although sometimes it crashes with a window that says 'Parsing DICOM files' that doesn't go away until I completely exit Python.

Without checking 'import uncategorized ROIs' in step 3, the import seems to go through; I am able to query things like 'Patient Sex' etc. DVHs, Endpoints, etc are always empty is this situation - probably because all the ROIs in my particular DICOM are uncategorized, so there aren't any contours in the data to build DVHs from. Will try to get screenshots of this. 

Any assistance would be greatly appreciated.

**Comment by cutright** [comment]
Do you have another planning system to try by chance?  These issues appear to be with XiO.

I'm not familiar with the TransferSyntaxUID DICOM tag.  @bastula Maybe dicompyler uses this?

**Comment by ThirumuruganE** [comment]
I am also facing the same issue. I am using Monaco version5. it says strptime() argument 1 must be a string.
![Screenshot from 2019-12-10 11-02-32](https://user-images.githubusercontent.com/26036836/70498540-bcef2b80-1b3c-11ea-97eb-a01e1b29a2e5.png)

**Comment by DVHmonkey** [comment]
> Do you have another planning system to try by chance? These issues appear to be with XiO.
> 
> I'm not familiar with the TransferSyntaxUID DICOM tag. @bastula Maybe dicompyler uses this?

Unfortunately the facility here only uses Xio; will ask the medical physicists in my facility for more info.

**Comment by cutright** [comment]
It appears as though you each have different issues.
* TransferSyntaxUID
* a join issue (probably a str.join)

It looks like strptime() is only used twice and it happens to have a try/except clause that prints the error but moves on.  So that's not the hangup here.
https://github.com/cutright/DVH-Analytics/blob/aab6dba2ec77dda07824d1f7815d892151e570a0/dvha/db/dicom_parser.py#L910-L916

If both of you could provide anonymized DICOM filesets demonstrating these issues, I'd be much more helpful.  Since I haven't implemented an error logger yet, I basically have to inject print statements in the code to figure out which line is causing the issue at this point.

**Comment by ThirumuruganE** [comment]
Thank you for the assistance!
I am currently a medical physics master's student and I am doing my project in a hospital. So, need to request physicist in the department. I will try my best to get permission from physicists in the department and send anonymized DICOM files.

**Comment by cutright** [comment]
Alternatively you could send me a plan from a phantom.  I'm sure they have something from commissioning, for example TG-119.  Just try to import that plan into DVHA first and make sure it reproduces the same error... I suspect it will if this is really a TPS issue.

**Comment by DVHmonkey** [comment]
Hi, thanks for the reply. Am communicating with the medical physicists here to get phantom DICOMs to try reproduce the error. Just for reference, one of them has in the past used patient DICOMs with the same format to recreate DVHs in R, Slicer and another third-party viewer he can't remember the name of.

**Comment by DVHmonkey** [comment]
Sorry for the repeated comments. I am still working on getting the phantom DICOMs, but clinic hours here are pretty hectic. Just wanted to share something about TransferSyntaxUID that I found.

I was fiddling with dicompyler-core on the study set via command line in Spyder (study opens and displays DVHs correctly in the dicompyler GUI application), and it gave a TransferSyntaxUID error attributed to pydicom. I then tried fiddling with pydicom to see if I could reproduce the error, code and terminal output below:.

![1](https://user-images.githubusercontent.com/58673531/70686653-56ab0a00-1cf0-11ea-8742-aa7c10d11da5.jpg)
![2](https://user-images.githubusercontent.com/58673531/70686661-5c085480-1cf0-11ea-9201-d9bb43911100.jpg)

Added a line to make it assume a TransferSyntaxUID (most probably the study set exported from the TPS in my facility doesn't have TransferSyntaxUIDs)
![3](https://user-images.githubusercontent.com/58673531/70686859-db962380-1cf0-11ea-8507-853ed21cec41.jpg)
).
![4](https://user-images.githubusercontent.com/58673531/70687101-7abb1b00-1cf1-11ea-845e-f659340f8138.jpg)

Did some searching around, found some information, but don't how relevant it is.
https://github.com/pydicom/pydicom/issues/590
https://github.com/pydicom/pydicom/issues/584

**Comment by bastula** [comment]
This all rings a bell. I brought this up in pydicom and even a fix 🤣 some time ago because I ran into the same issue. It didn't make it into pydicom, but you can apply the fix locally in DVHA.

Please see: https://github.com/pydicom/pydicom/pull/341 / https://github.com/pydicom/pydicom/pull/342

**Comment by cutright** [comment]
Thanks everyone. I think I understand the problem now, from the pydicom side anyway.  I'll need to do some digging find out everywhere it shows up in DVHA.

@bastula If I move all of my code to use `dicompylercore.dicomparser.DicomParser()` instead of `pydicom.read_file()`, would that resolve this issue?  Currently I use both (sometimes together)... but that's not particularly efficient and an artifact of learning python as I built DVHA.  I suspect I only need dicompylercore.  Is there any overhead benefit to using `pydicom.read_file()` over dicompylercore when I only want a single tag, for example checking for Modality?

@DVHmonkey If you could still send an anonymized set of DICOM RT Struct, Dose, and Plan files, it would be very helpful.  I could also quickly address any other potential import issues that show up after this fix.

**Comment by DVHmonkey** [comment]
Thanks for your response. I've obtained water phantom DICOMs from commissioning but was only provided Dose, Structures and Plan - would the images be needed as well? Should I send them directly to your work email (searched on Google), or use a free online file sharing service?

**Comment by cutright** [comment]
No imaging needed. Email should be OK.

**Comment by DVHmonkey** [comment]
I just found out I could upload zips on github. The phantom dicoms are attached below.

[WATER PHANTOM DICOMS.zip](https://github.com/cutright/DVH-Analytics/files/3958681/WATER.PHANTOM.DICOMS.zip)

**Comment by cutright** [comment]
@bastula Any thoughts from below?  DVHA faults when calling `dicompylercore.dvhcalc.get_dvh()`.

I get the TransferSyntaxUID error with the simple code below.

```
from dicompylercore import dvhcalc
dvh = dvhcalc.get_dvh('SS.rtp1.6.water.60.dcm', 'DOSE.water.60_dicomtest.dcm', 1)
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/Users/nightowl/PycharmProjects/DVH-Analytics/venv/lib/python3.6/site-packages/dicompylercore/dvhcalc.py", line 75, in get_dvh
    callback)
  File "/Users/nightowl/PycharmProjects/DVH-Analytics/venv/lib/python3.6/site-packages/dicompylercore/dvhcalc.py", line 125, in calculate_dvh
    dd = dose.GetDoseData()
  File "/Users/nightowl/PycharmProjects/DVH-Analytics/venv/lib/python3.6/site-packages/dicompylercore/dicomparser.py", line 761, in GetDoseData
    data = self.GetImageData()
  File "/Users/nightowl/PycharmProjects/DVH-Analytics/venv/lib/python3.6/site-packages/dicompylercore/dicomparser.py", line 247, in GetImageData
    self.ds.file_meta.TransferSyntaxUID.is_little_endian
  File "/Users/nightowl/PycharmProjects/DVH-Analytics/venv/lib/python3.6/site-packages/pydicom/dataset.py", line 745, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Dataset' object has no attribute 'TransferSyntaxUID'
```

I also naively tried using setattr() to dose and structure datasets prior to passing them into `dvhcalc.get_dvh()` but no luck.

Curiously, opening these files with the compiled dicompyler application (v0.4.2) works fine.  Is dicompyler doing something dicompyler-core is not?

**Comment by bastula** [comment]
This is a change specific to `pydicom` 1.0 and above. Since the compiled dicompyler uses `pydicom` 0.9.8 or below it doesn't affect it. You have to manually set the transfer syntax either by patching `pydicom` by my PR here: https://github.com/pydicom/pydicom/pull/342 or using a fix in DVHA as suggested here: https://github.com/pydicom/pydicom/pull/342#issuecomment-377519820

**Comment by cutright** [comment]
@DVHmonkey Long story short, the latest master (v0.6.3) now works with your supplied files.

-----------------------
Just to post the current status to the thread:
I think I'm having some environmental issues with pynetdicom3 when using it in DVHA - that is, I couldn't launch it from the terminal with `python dvha_app.py` but I could launch it just fine from within a python console with `dvha.start()`.  However, I can get by without pynetdicom.  The simple code below works:

```
from dicompylercore.dvhcalc import get_dvh
import pydicom
from pydicom.uid import ImplicitVRLittleEndian

def validate_transfer_syntax_uid(data_set):
    meta = pydicom.Dataset()
    meta.ImplementationClassUID = pydicom.uid.generate_uid()
    meta.TransferSyntaxUID = ImplicitVRLittleEndian
    new_data_set = pydicom.FileDataset(filename_or_obj=None, dataset=data_set, is_little_endian=True,
                                       file_meta=meta)
    new_data_set.is_little_endian = True
    new_data_set.is_implicit_VR = True
    return new_data_set

ds_struct = pydicom.read_file('SS.rtp1.6.water.60.dcm', force=True)
ds_struct = validate_transfer_syntax_uid(ds_struct)
ds_dose = pydicom.read_file('DOSE.water.60_dicomtest.dcm', force=True)
ds_dose = validate_transfer_syntax_uid(ds_dose)
dvh = get_dvh(ds_struct, ds_dose, 1)
```

@bastula Do you foresee any issues using `pydicom.uid.generate_uid()` instead of `pynetdicom.PYNETDICOM_UID_PREFIX`?

**Comment by cutright** [comment]
@ThirumuruganE I'm sorry, after looking at your comment again I realized your issue looks to be unrelated.  I don't believe the string error is causing the fault, that message is simply printed.  I don't believe `datetime.strptime()` is used anywhere other than here:
https://github.com/cutright/DVH-Analytics/blob/900b3df6e97ba7331db6914fb97463f609595b4e/dvha/db/dicom_parser.py#L919-L925

Everywhere that uses that function `DICOM_Parser.get_time_stamp()` is able to accept `None` type, which is what is returned in your case.  The real error is related to the string `join()` function which is used fairly frequently.

If you can provide some DICOM files (anonymized or on a phantom), I can take a closer look and likely create a new issue.

**Comment by DVHmonkey** [comment]
Hi, got in to work today and tested it out. Thanks for working on it over the weekend. I've successfully imported an actual patient's data, looking forward to testing it with a larger sample, will report back. For now, with only 1 study I can't seem to view DVHs or plot anything.

Thanks and regards.

**Comment by cutright** [comment]
No problem, glad it's working.

With respect to 1 study, it should still work.  Perhaps it didn't import any DVHs because no ROI map was applied and "Import uncategorized ROIs" wasn't checked?
