### ISSUE TITLE
Compute overlap between 2 structures

### ISSUE THREAD

**Issue by sama2689** [cutright/DVH-Analytics#160]
I am trying to use dicompylercore with dvha to compute the overlap between two structures from their list of coordinates. I am using dicompylercore's [`GetStructureCoordinates`](https://dicompyler-core.readthedocs.io/en/latest/dicompylercore.html#dicompylercore.dicomparser.DicomParser.GetStructureCoordinates) method in combination with `dvha`'s [overlap_volume](overlap_volume) method.

If I understand correctly, the input of overlap_volume is a pair of dicts returned by calling `GetStructureCoordinates`, and so this is what I am doing.

However, in running a simple test of this, I find that PTV and GTV overlap volume is 0 (which of course isn't possible). Are there any obvious problems with this code?

```
from dicompylercore import dicomparser, dvh, dvhcalc
from dvha.tools.roi_geometry import overlap_volume
dp = dicomparser.DicomParser("RT-STRUCT.dcm") #parse RTStruct dicom

# i.e. Get a dict of structure information
structures = dp.GetStructures() #can use this structures dict to find structure indices

GTV_coords=dp.GetStructureCoordinates(16) #GTV coordinates, GTV index is 16
PTV_coords=dp.GetStructureCoordinates(18) #PTV coordinates, PTV index is 18


v=overlap_volume(PTV_coords, GTV_coords)
```

For some reason I keep getting v=0 which makes no sense. Trying with other structure combinations also yields consisted 0 overlap volumes, so I suspect that I have made some mistake in how I call the overlap_volume function or in what format the inputs are in.

Any help appreciated, and fantastic work on the package!

**Comment by cutright** [comment]
Please see my comment from the [dicompyler-core issue](https://github.com/dicompyler/dicompyler-core/issues/223#issuecomment-832055803) you posted, the formats are different. `overlap_volume` needs a "sets of points" format

I might be easier to write a function to convert dicompyler-core structure coordinates into Shapely objects.  Then use Shapely's geometric operations to get intersections.  The DVHA code can provide some good inspiration for that.

That said, I haven't tried the following, but seems like it should work.  You can use a couple functions already written to get what you need I think.

https://github.com/cutright/DVH-Analytics/blob/b0be7031ccf7f8ef33dc26b441c02a9bbc3efc9c/dvha/tools/roi_formatter.py#L201-L223

https://github.com/cutright/DVH-Analytics/blob/b0be7031ccf7f8ef33dc26b441c02a9bbc3efc9c/dvha/tools/roi_formatter.py#L38-L71

**Comment by sama2689** [comment]
That works! Leaving this working example below in case anyone else wants to try it.

```
from dicompylercore import dicomparser, dvh, dvhcalc
from dvha.tools.roi_geometry import overlap_volume
from dvha.tools.roi_formatter import dicompyler_roi_coord_to_db_string, get_planes_from_string

dp = dicomparser.DicomParser("RT-STRUCT.dcm") #parse RTStruct dicom

# i.e. Get a dict of structure information
structures = dp.GetStructures() #can use this structures dict to find structure indices

#extract gtv and format for dvha (with this specific rt-struct file 16 is the gtv index)
gtv_coords=dp.GetStructureCoordinates(16)
gtv_coords_str=dicompyler_roi_coord_to_db_string(gtv_coords)
gtv_planes=get_planes_from_string(gtv_coords_str)

#do the same for ptv (with this specific rt-struct file 18 is the ptv index)
ptv_coords=dp.GetStructureCoordinates(18)
ptv_coords_str=dicompyler_roi_coord_to_db_string(ptv_coords)
ptv_planes=get_planes_from_string(ptv_coords_str)



v=overlap_volume(ptv_planes, gtv_planes)
```
