### ISSUE TITLE
Possible issue with the sort call in get_shapely_from_sets_of_point function

### ISSUE THREAD

**Issue by sama2689** [cutright/DVH-Analytics#164]
I am deploying the `get_shapely_from_sets_of_points`  with a sets of points formatted dictionary. The keys in my particular sets of points dict (which I have extracted using `get_planes_from_string(dicompyler_roi_coord_to_db_string(parsed_rt_struct.GetStructureCoordinates(structure_id)))`) are as follows :`['-10.5', '-7.5', '-4.5', '1.5', '-1.5', '4.5', '13.5', '10.5', '7.5', '16.5', '19.5', '22.5', '25.5']`

When sorted this list should look like `['-10.5', '-7.5' , '-4.5', '-1.5', '1.5', '4.5', '7.5', '10.5', '13.5', '16.5', '19.5', '22.5', '25.5']`. So the thickness should essentially be a constant 3.0.

However when I put my sets of points dict into the get_shapely_from_sets_of_point function, I noticed that the thicknesses are incorrect. I have traced the cause of this to the sort call in [`get_shapely_from_sets_of_points`](https://dvha.readthedocs.io/en/latest/_modules/dvha/tools/roi_formatter.html#get_shapely_from_sets_of_points)

When the function calls for the keys of my sets of points dict this returns the list `['-10.5', '-7.5', '-4.5', '1.5', '-1.5', '4.5', '13.5', '10.5', '7.5', '16.5', '19.5', '22.5', '25.5']`

When the sort call is applied to this list, the output is `['-1.5', '-10.5', '-4.5', '-7.5', '1.5', '10.5', '13.5', '16.5', '19.5', '22.5', '25.5', '4.5', '7.5']`. The sort call is not correctly sorting these (because they are strings), and so when the function later goes to compute thicknesses, the thicknesses are incorrect. This can be fixed by converting to float before sort is called and then converting back. i.e. 
```
sets_of_points_keys = [float(key) for key in list(sets_of_points)]
sets_of_points_keys.sort()
sets_of_points_keys=[str(key) for key in sets_of_points_keys]

```

**Comment by cutright** [comment]
Good catch. I think the decimal precision with a `str` call may be an issue in some cases though (i.e., trailing zeros)?

I think the simplest fix is to remove the `sets_of_points_keys` all together, and then sort `all_z_values` before the thickness calculation.
https://github.com/cutright/DVH-Analytics/blob/a168cf67709b7a60d0d311a294801954421c1ad1/dvha/tools/roi_formatter.py#L253-L261

So remove lines 253-254 and change line 256 to this:
```
all_z_values = sorted([round(float(z), 2) for z in sets_of_points])
```

That said, the code feels sloppy to me, I'll probably clean it up a bit before pushing.

I only found one use of this thickness calculation in DVHA (surface area), and even there it only used the minimum value. Thankfully, this is a pretty minimal impact to DVHA users.

https://github.com/cutright/DVH-Analytics/blob/a168cf67709b7a60d0d311a294801954421c1ad1/dvha/tools/roi_geometry.py#L221-L228

**Comment by cutright** [comment]
I only did one test import so far. All surface area calculations were identical except for my external ROI, which was way off.

I still think this can be done more concisely, but at least this avoids calling `index` based on type-converted values.

https://github.com/cutright/DVH-Analytics/blob/29a5fa31fbd20f16b1a8779ef3c9081e4134c898/dvha/tools/roi_formatter.py#L253-L275
