### ISSUE TITLE
Posible Memory leaek

### ISSUE THREAD

**Issue by bozhikovstanislav** [cutright/DVH-Analytics#166]
Hi

I am testing the calculation of Distance Matrix on a linux machne .
and found that the calculation take 46 GB of swap +16 GB of RAM to calculate the results ...

**Comment by cutright** [comment]
Is the memory recovered after the calculation?

Can you be more specific? I'm pretty sure any time the GUI uses the distance calculation algorithm it attempts to calculate all at once except on MemoryError, then it performs it in chunks instead.  But maybe I missed one?

For example:
https://github.com/cutright/DVH-Analytics/commit/8490db62bd67b5495a4a779c015f2776023f4dd2

**Comment by bozhikovstanislav** [comment]
Yes it recovers but takes a lot of the memory . and swap space also.

No I am calculating 2094 Studies it take 340 per day to calculate
And this is  on my laptop hehehehe.....
Never stops ..

**Comment by bozhikovstanislav** [comment]
I was thinking about how high resolution structure may consume more Ram ????

**Comment by cutright** [comment]
Can you test that by reducing the small-volume threshold?  Then see if it goes away?  You can also adjust the number of interpolated slices and in-plane interpolation factor in DVHA settings.

If there is a `MemoryError`, the calculation is done in chunks as long as you're on `dicompyler-core >=0.5.6`. I could add an option to always turn on memory mapping and DTH/OVH calculation in chunks... but it would guarantee a slower calculation when it maybe wasn't needed?

You could track it down with python's memory profiler.  That's how I managed to remove the memory leaks in Windows.
https://towardsdatascience.com/profile-memory-consumption-of-python-functions-in-a-single-line-of-code-6403101db419

Just curious, what resolution are your dose grids?

**Comment by bozhikovstanislav** [comment]
WOW it works faster now after adjusting what you say .. Thanks
