### ISSUE TITLE
PIP install version crashes with ModuleNotFoundError: No module named 'paths'

### ISSUE THREAD

**Issue by GregSal** [cutright/DVH-Analytics#22]
The following is the output from PIP:
```
(DVH) C:\>pip install dvh-analytics
Collecting dvh-analytics
  Using cached https://files.pythonhosted.org/packages/e2/f9/d4ecc88b641276c4c896901fae493a663a9c7e9399a191e2ff1476d0592c/dvh-analytics-0.5.11.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\gsalomon\anaconda3\envs\DVH\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"
'C:\\Users\\gsalomon\\AppData\\Local\\Temp\\pip-install-w8bw_quw\\dvh-analytics\\setup.py'"'"'; __file__='"'"'C:\\Users\
\gsalomon\\AppData\\Local\\Temp\\pip-install-w8bw_quw\\dvh-analytics\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"',
open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"
'))' egg_info --egg-base 'C:\Users\gsalomon\AppData\Local\Temp\pip-install-w8bw_quw\dvh-analytics\pip-egg-info'
         cwd: C:\Users\gsalomon\AppData\Local\Temp\pip-install-w8bw_quw\dvh-analytics\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\gsalomon\AppData\Local\Temp\pip-install-w8bw_quw\dvh-analytics\setup.py", line 2, in <module>
        from dvh.modules.default_options import VERSION
      File "C:\Users\gsalomon\AppData\Local\Temp\pip-install-w8bw_quw\dvh-analytics\dvh\modules\default_options.py", line 8, in <module>
        import paths
    ModuleNotFoundError: No module named 'paths'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Using Anaconda environment with Python 3.7
All listed dependencies already installed:
[DVH Packages.txt](https://github.com/cutright/DVH-Analytics/files/4019535/DVH.Packages.txt)

**Comment by cutright** [comment]
Frankly, I have not kept up with the PyPI uploads, particularly for any version with wxPython.  I'll take a look this weekend to see if I can get a pip install to work with the current version of DVHA.

In the meantime, I'd recommend cloning the source code and running as recommended in the [installation notes](https://github.com/cutright/DVH-Analytics/blob/master/install_notes.md).

On a related note, I am close to creating an executable version of DVHA, then you won't have to deal with python.  I think it's ready for MacOS, but MS Windows still has some dll issues.

**Comment by cutright** [comment]
I think I've got it working now.  I'd go ahead and uninstall what you have with `pip uninstall dvh-analytics`

Then do a `pip install dvha` which should give you version 0.6.3.  Launch by typing `dvha` in the terminal.  If this works for you, I'll update the readme and installation notes.  Thanks for posting, I've been procrastinating this for a long time and it turned out to be an easy fix.

I just needed to update MANIFEST.in to properly include all of the non-python files it was missing.

I suspect the issue related to the printout in your comment above is related to relative vs absolute imports, but it's for the old web-based version of DVHA.  I may just delete all of those from PyPI since I'm not maintaining that code anymore.

**Comment by GregSal** [comment]
Hi Dan,
  The pip install works now.  I haven't tried running it yet.

BTW.  I had a quick read of the Control Charts paper pre-print.  It looks
great!  I hope you are successful in convincing your colleagues to adopt
some of the practices you described.  I struggled for a while to get my
fellow physicists at our centre to start using them for tracking our
routine QA work, but I ended up giving up.  I hope that you will have more
success than I did.  It may not be easy.  Even Todd Pawlicki said that he
has had difficulties getting people at his centre to accept the use of
control charts.

Thanks again for your work on this software.  It is much appreciated.
Greg Salomons

**Comment by cutright** [comment]
Thanks Greg!  Yeah, I haven't implemented control charts routinely yet either.  But one of my long-term goals is to add a report builder in DVHA aimed at initial physics chart checks.  We also have a pretty neat [DICOM-RT structure identification algorithm](https://uchicago.technologypublisher.com/technology/36434) in the works which should help with this.

On a related note, I've just added control charts to my [IMRT QA Data Miner](https://github.com/cutright/IMRT-QA-Data-Miner) project.  Hopefully it'll make it easier to follow TG-218's recommendations.  It's still in development, but I hope to button it up for easier use in the next month or two.
