### ISSUE TITLE
Executable build with PyInstaller

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#23]
I'm adding this partially to help me remember what I've done, and partially in hopes that someone with more experience out there might be able to help.  

I *think* I have successfully compiled DVHA for macOS Mojave. You can give this a try by downloading DVHA_macOS_Mojave.zip on the [releases page](https://github.com/cutright/DVH-Analytics/releases) - or directly download with this hard link to 0.6.3 (+ minor fixes) [here](https://github.com/cutright/DVH-Analytics/releases/download/v0.6.3/DVHA_macOS_Mojave.zip).  Your browser may automatically unzip this file which contains a single app, double click to run. You may need to enable this app in System Preferences -> Security & Privacy -> Open Anyway.  

<img width="532" alt="Screen Shot 2020-01-04 at 10 09 36 AM" src="https://user-images.githubusercontent.com/4778878/71768280-65917080-2eda-11ea-866c-053491cb1e3e.png">

<img width="780" alt="Screen Shot 2020-01-04 at 10 05 57 AM" src="https://user-images.githubusercontent.com/4778878/71768691-29f8a580-2ede-11ea-974d-c0b7822b9ede.png">

Here is the Pyinstaller spec file I used:
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['dvha_app.py'],
             pathex=['./',
                     './venv/lib/python3.6/site-packages'],
             binaries=[('/System/Library/Frameworks/Tk.framework/Tk', 'tk'),
                       ('/System/Library/Frameworks/Tcl.framework/Tcl', 'tcl')],
             datas=[('./dvha/icons/', './dvha/icons/'),
                    ('./dvha/logo.png', './dvha/'),
                    ('./dvha/LICENSE', './dvha/'),
                    ('./dvha/db/create_tables.sql', './dvha/db/'),
                    ('./dvha/db/institutional.roi', './dvha/db/'),
                    ('./dvha/db/physician_BBM.roi', './dvha/db/')],
             hiddenimports=['sklearn.utils._cython_blas',
                            'sklearn.neighbors._typedefs',
                            'sklearn.neighbors._quad_tree',
                            'sklearn.tree._utils'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='dvha_app',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False)
app = BUNDLE(exe,
             name='DVH Analytics',
             icon='./dvha/icon.jpg',
             bundle_identifier=None,
             info_plist={'NSHighResolutionCapable': 'True'}
             )

```

For MS Windows,  I've successfully packaged an executable that works on my PC, but no one else's... so I suspect there's some more dll files I'm missing.  I also ran into issues with SciPy because it moved its dll files, but I got around this by downgrading SciPy by one version.  I'll post my MSW spec file on Monday (I left it at work).

**Comment by mchamberland** [comment]
For what it's worth, the Mac version runs on Catalina, too. But I don't have a database set up on my laptop or plan files to test it with.

**Comment by cutright** [comment]
Here is my .spec file for MS Windows.  Successful compilation on my PC with Windows 7 Enterprise Service Pack 1.  Intel Core i5.  I couldn't catch the text of the terminal because I can't get it to stay open, but below is a screen shot of the ouput.

Looks like PyInstaller is saving some absolute paths instead of relative?

```
# -*- mode: python ; coding: utf-8 -*-

# Windows fails with scipy >= 1.3.0  (needs the extra-dll folder in package)

block_cipher = None


a = Analysis(['dvha_app.py'],
             pathex=[r".",
                     r".\venv\Lib\site-packages"],
             binaries=[],
             datas=[(r".\dvha\icons", r".\dvha\icons"),
                    (r".\dvha\logo.png", r".\dvha"),
                    (r".\dvha\LICENSE", r".\dvha"),
                    (r".\dvha\db\create_tables.sql", r".\dvha\db"),
                    (r".\dvha\db\institutional.roi", r".\dvha\db"),
                    (r".\dvha\db\physician_BBM.roi", r".\dvha\db")],
             hiddenimports=['sklearn.utils._cython_blas',
                            'sklearn.neighbors._typedefs',
                            'sklearn.neighbors._quad_tree',
                            'sklearn.tree._utils'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='dvha_app',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True)
app = BUNDLE(exe,
             name='DVH Analytics',
             icon=r".\dvha.ico",
             bundle_identifier=None,
             info_plist={'NSHighResolutionCapable': 'True'}
             )
```

![image](https://user-images.githubusercontent.com/4778878/71832838-5bee4100-3071-11ea-9d55-6df1741fd246.png)

**Comment by cutright** [comment]
I since added my venv to datas, still getting an error.

@mchamberland I wonder if the uploaded binary only worked on your mac because you already had the appropriate python libraries installed?

![image](https://user-images.githubusercontent.com/4778878/71834381-b6d56780-3074-11ea-87d0-b76c2b8ee405.png)

**Comment by cutright** [comment]
Success!! Will try to post an executable tomorrow along with a version update.

I should have read the output more closely.  The issue is sklearn.

I edited sklearn hooks per [this post](https://stackoverflow.com/questions/49559770/how-do-you-resolve-hidden-imports-not-found-warnings-in-pyinstaller-for-scipy)

And also had to downgrade scikit-learn to 0.21.
* scikit-learn==0.22.1 doesn't work with DVHA at all
* scikit-learn==0.22 didn't work with pyinstaller==3.6


I think the "reference" to user folder of my compiling PC is actually a hard-coded string of a warning output, not that the executable is trying to access that file path.

I also upgraded pip to latest dev and used setuptools==44.0.0.  Will have to test if sklearn is the only issue.  PyInstaller and setuptools==45.0.0 aren't playing well together: https://github.com/pypa/setuptools/issues/1963

Next step is to see if there are ways to trim down the included libraries and get the executable file size smaller?

**Comment by bastula** [comment]
Scipy is a big culprit if you don't need it but I am sure it's a required dependency for scikit-learn.

**Comment by cutright** [comment]
Yes, unfortunately.  I also use it for PTV distance calculations.

**Comment by cutright** [comment]
I was able to trim 20MB from bokeh per my post over on bokeh's community page
https://discourse.bokeh.org/t/reducing-bokeh-footprint-in-venv-for-pyinstaller/4622/2

**Comment by cutright** [comment]
I still plan to try reducing executable size, but since the executables appear to be working I'm closing the issue.
