### ISSUE TITLE
FileNotFoundError on Windows 10 after installing with setup.py

### ISSUE THREAD

**Issue by mchamberland** [cutright/DVH-Analytics#28]
I tried the latest version (0.6.7) on Windows 10. After unzipping the source code, I ran

`python setup.py install`

Then, when launching from the command line with `dvha`, I got two `FileNotFoundErrors`: it's looking for `institutional.roi` and `physician_BBM.roi`.

Current workaround is just to create those two blank files in the folder where it's looking.

**Comment by cutright** [comment]
Ugh... found the issue, typo in MANIFEST.in

https://github.com/cutright/DVH-Analytics/blob/9af8f65cab4d6991b3dd7179c0f93735b49daf6c/MANIFEST.in#L8

**Comment by cutright** [comment]
Thanks Marc, hope the SQLite works out for you in your clinic

**Comment by mchamberland** [comment]
This is great! I was able to install and import some plans.

Now, I just need a student to do the grunt work of export / import...
