### ISSUE TITLE
DICOMparser -> get value of a private DICOM-tag

### ISSUE THREAD

**Issue by Kiragroh** [cutright/DVH-Analytics#38]
Hi,

very nice work so far.

If it possible to get the content from a DICOM-object without Tag-name? It seems that the pydicom_attribute has to be the TagName but many tags only have the number "(0xx,00xx)". 

I want to change the BeamName-Property because in Eclipse-plans the BeamName has no TagName (only the BeamID has a TagName ("BeamName"^^).

For instance this is what I tried but no luck:
 self.rt_data['plan'].PatientID
 -> self.rt_data['plan'].pydicom.tag.Tag(0010,0040)

Solution:
....
    'protocol': [self.tps_protocol_hack, 'text'],
....

 @property
    def tps_protocol_hack(self):
        if 'xxy' in self.rt_data['plan'].BeamSequence[0][0x3243,0x1009].value.decode('utf-8'):
            ans = 'xxy2'
        elif 'xxz' in self.rt_data['plan'].BeamSequence[0][0x3243,0x1009].value.decode('utf-8'):
            ans = 'xxz2'
        elif self.rt_data['plan'].BeamSequence[0][0x3243,0x1009].value.decode('utf-8').startswith('Xxw'):
            ans = 'xxw2'
        else:
            ans = 'DEFAULT'
        return ans

**Comment by cutright** [comment]
Thanks @Kiragroh 

`self.rt_data['plan']` is the output from a `pydicom.read_file()`, so you shouldn't need the pydicom in that line.

If I understand you correctly, it would be helpful to add this into DVHA for everyone who uses Eclipse (and perhaps others). I could edit this function below to accommodate:
https://github.com/cutright/DVH-Analytics/blob/f3b86329ec4b76d870a6a7b9b86d4340a7a48b0c/dvha/db/dicom_parser.py#L1112-L1117

I have Eclipse here in my clinic, I'll poke around this afternoon.

**Comment by Kiragroh** [comment]
Thanks for the reply. 
My goal is to query with a private tag. 
In Eclipse the Field-Id is found behind the DICOM-Tag 'BeamName' and the Field-Name is hidden behind a private tag. Because of a specific data set I would need to access the Field-Name.
I attached a screenshot:
![screenshot_328](https://user-images.githubusercontent.com/44711812/72925491-14df9b80-3d53-11ea-9424-4112b7c89af7.png)

**Comment by cutright** [comment]
If you want to access a private tag, you can do so by using the tag as a key, similar to the following:
```
>>> import pydicom
>>> ds = pydicom.read_file('RTPlanTest.dcm')
>>> ds.BeamSequence[0][0x300a,0x00c2]
(300a, 00c2) Beam Name                           LO: '01 CCW'
>>> ds.BeamSequence[0][0x300a,0x00c2].value
'01 CCW'
```

My Eclipse version does not have the private tag you indicate.  Which version are you on?  Is the indicated private tag the beam name the user typed in or something automated?

I've begun writing a user manual and subsequently I'm tabulating all of the DICOM tags I'm using.  I suppose long term I should have DVHA look up the tag from a table and allow users to specify different tags if they wish.  Doable... but not trivial.

**Comment by Kiragroh** [comment]
Thank you very much. 
Eclipse 15.1
It is the long field-name under the field-Id if you open the field properties. Normally manual user input is required but in my case, there is an automatic aspect from a third-party planning system.

**Comment by cutright** [comment]
Oh interesting.  Perhaps I don't have that tag because that field was left blank.

I think deviating from the current beam name order and tags should require some user input (via the user settings window) to implement generally.

If you don't mind me asking, what is the context for wanting this value in your query?  Maybe there's another way I can approach the problem more generally for other users?  Or perhaps I'm calculating other values already that may do what you're looking for?

I was going to suggest a script you could run after DVHA import, to update beam names based on extracted DICOM tag values, but I realize now my DICOM_Files SQL table is lacking some information if you have multiple plan files for a given StudyInstanceUID.  I should implement proper table row UIDs / primary keys throughout, instead of depending on StudyInstanceUID so heavily.

**Comment by Kiragroh** [comment]
No problem.

My third-party planning system has 3 planning modules and after export from this system and later import in Eclipse (for treatment with TrueBeam machine) the only DICOM identifier of these modules for data mining and automatic analysis is this field-name. 
If I can read this tag I can build a property for these modules (if fieldname is this then it has to be this module) or replace a property I don't need to query in DVHA for further analysis.

I think it would be a good idea to give the user the possibility to add certain properties to make more specific queries but I understand that this is not trivial.

**Comment by cutright** [comment]
So I'm working on generating tables like the one below for the user manual.  All are complete except Beams.  I think what I could do is store these DICOM tags in a table and have DICOM_Parser() look up the tag, then build a simple interface in DVHA that lets you over-ride the DICOM tag.  I think that would solve your problem?

There's a lot of code to update, but I like that it generalizes the import process more... and makes things a little more transparent.  I could probably knock that out by next week, at least in a dev branch.

<img width="553" alt="Screen Shot 2020-01-22 at 4 22 55 PM" src="https://user-images.githubusercontent.com/4778878/72939936-83acfc80-3d33-11ea-9f55-7b3ca27b4340.png">

**Comment by Kiragroh** [comment]
Solution in initial question.
