### ISSUE TITLE
DVH Endpoint Constraint Evaluation

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#53]
I plan to merge the code for [DVH Check](https://github.com/cutright/DVH-Check) into DVHA.  This will probably include a standalone plan viewer (*i.e.*, view DVHs and stats for a plan without importing into your database).

**Comment by bastula** [comment]
TBH this will significantly increase usage from the general population of clinics! A good move!

**Comment by Kiragroh** [comment]
Please do this. I had tried to use DVH Check routinely but it crashes after the first use and sometimes doesn't responds. Would be a nice addition to a very very nice tool.

**Comment by cutright** [comment]
Yeah, sorry about that... I wrote DVH Check really quickly for a clinical need that evaporated.  So it never got the attention it deserved.  I've got some good ideas for DVHA though, I plan to let you incorporate constraint pass/fail status into your query.
