### ISSUE TITLE
Delete Database is not working in v.07.4

### ISSUE THREAD

**Issue by Kiragroh** [cutright/DVH-Analytics#55]
Hi,

I like DVHA very much but for testing I often delete the database. This function is not working anymore. Something about a missing option. Sadly I am not able to fix this.

There is a workaround. Press 'rebuild database', quit the importer and delete or move the files in the imported folder.

Please keep up the good work.

**Comment by cutright** [comment]
Sorry about that, it should be an easy fix.  I'll take a look this evening.

Are you using SQLite or PostgreSQL?  Are you running from source, or would you need a new executable?

**Comment by Kiragroh** [comment]
Thanks for the quick reply.
I use Source Code with PyCharm on Mac with PostgreSQL.
I am glad if you could add a fix for the next bigger update. The workaround is fine for me. :)

**Comment by cutright** [comment]
Should be fixed in the 0.7.5dev branch.

I learned I should call `VACUUM` after dropping tables, at least in SQLite... might also apply to Postgres.  I'll have to look into it.
