### ISSUE TITLE
DICOM Tag Editor

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#61]
I built a DICOM tag editor today: [DVHA DICOM Editor](https://github.com/cutright/DVHA-DICOM-Editor).

I know there are other solutions out there, but all of the ones I found either cost money, require admin rights or an installation, or are command-line only.  So maybe there's some space out there for this project.

Long story short, I think there's some utility for a DICOM tag editor in DVHA... particularly with users working with anonymized or phantom data. I plan to merge this code into DVHA by v0.9.

NOTE: As of v0.2, only non-sequence tag values are supported

<img src='https://user-images.githubusercontent.com/4778878/77604220-f7a88400-6edf-11ea-9dca-21492ca8cf73.png' align='center' width='400' alt="DVH Analytics screenshot">

**Comment by cutright** [comment]
I've just added the ability to dynamically set DICOM tag values based on file path or tag value.  I also added a window to search for DICOM Tags.  Still to do:
* Sub-directory searching
* Editing tags that are within a sequence
* Better data type handling
* A function similar to the file enumerator `fenum`, but generates DICOM compliant UIDs

Open to other features if anyone has suggestions.

DICOM Tag Search
---------
<img width="784" alt="Screen Shot 2020-03-29 at 5 55 07 PM" src="https://user-images.githubusercontent.com/4778878/77863227-71918380-71e6-11ea-9b51-24da72a069d1.png">


Dynamic Value Setting
---------
Users can dynamically define DICOM tag values with one of the functions below, which are denoted by asterisk-pairs.

Available functions:
* `dir[n]`: insert the n<sup>th</sup> component of the file path
* `fenum[n]`: insert an iterator based on the  n<sup>th</sup> component of the file path
* `venum[n]`: insert an iterator based on the tag value, n=-1 being tag value, n=-2 the parent value, etc. 
(NOTE: only n=-1 is currently supported)

### Examples
For a directory `/some/file/path/ANON0001/` containing files `file_1.dcm`, `file_2.dcm`:
* *Directory*:
    * NOTE: file extensions are removed
    * `some_string_*dir[-1]*`
        * some_string_file_1
        * some_string_file_2
    * `*dir[-2]*_AnotherString`
        * ANON0001_AnotherString
        * ANON0001_AnotherString
* *File Enumeration*:
    * `some_string_*fenum[-1]*`
        * some_string_1
        * some_string_2
    * `*fenum[-2]*_AnotherString`
        * 1_AnotherString
        * 1_AnotherString
* *Value Enumeration*:
    * NOTE: Assume each file has the same StudyInstanceUID but different SOPInstanceUIDs
    * `*dir[-2]*_*venum[-1]*` used with SOPInstanceUID tag
        * ANON0001_1
        * ANON0001_2
    * `*dir[-2]*_*venum[-1]*` used with StudyInstanceUID tag
        * ANON0001_1
        * ANON0001_1

**Comment by cutright** [comment]
This app is essentially complete now.  I've decided there isn't much utility into including in the DVH Analytics code explicitly.  So I'll just add a weblink to the releases page in the the DVHA app.

https://github.com/cutright/DVHA-DICOM-Editor

### Key Features
* No admin rights needed
* Executables provided, which require no installation  
* Create templates for routine tag editing
* Search for DICOM tags by keyword
* Dynamically define new DICOM tag values based on:
    * File paths
    * Initial DICOM tag values
    * DICOM compliant UIDs
        * Lookup DICOM prefixes
        * Set entropy source for UID generation
        * Maintain cross-file UID links
    * Randomly generated numbers

**Comment by Kiragroh** [comment]
Hi,
I nearly build my own DICOM-Editor too because I needed one that can change a DICOM-Tag of a whole Series. Reason: Sometimes there are CT-import problems in Eclipse because one character in one DICOM-Tag is not supported. If you can't edit the tag for the whole series you have to do it for every image (>100).
Luckily I found the free program 'DICOM-browser' (https://bitbucket.org/nrg/dicombrowser/downloads/v) that has this functionality. Maybe you want to check out the program for inspiration or add the mentioned feature.

**Comment by cutright** [comment]
Oh nice, thanks.  Yeah, DVHA DICOM Editor can do that as well.
