### ISSUE TITLE
Incorrect DVHs for FFS, HFP patient orientations  (non-HFS?)

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#62]
Multiple users have identified a bug where DVHs are incorrectly calculated for Foot-First-Supine patient orientations.  This appears to be an issue with `dicompyler-core` and can be observed by independently loading CT and RT-Structure data in the `dicompyler` GUI/program, the structures to do not line up with the CT.

Thanks to Mahesh and Mike for catching this.

Are there any other users out that that have observed similar behavior for other patient orientations?  It would be easy to check, simply include a Patient Orientation filter in your query.  The DVHs will almost certainly not monotonically decrease.

The resolution is unclear for the moment, but at a minimum I'll flag FFS plans in DVHA on import in `v0.7.5` when it's released.

**Comment by cutright** [comment]
Mike confirmed an issue with HFP as well.

**Comment by cutright** [comment]
As of v0.7.5, users will receive an error window after clicking on Import on the import screen, if any plans have non-HFS orientations.

**Comment by bastula** [comment]
Can you cross-post this issue on `dicompyler-core`'s issue tracker so I can start working on it there?

**Comment by cutright** [comment]
Needs testing, but looks like this is fixed here https://github.com/dicompyler/dicompyler-core/commit/57fbda8c7bfc6ffb952a1934ded318b227bfd3dc

A new `dicompyler-core` version is planned to be released shortly.  Will start testing with DVHA next week.

**Comment by cutright** [comment]
Tested a HFP import, looks to be working.  I'll include the latest `dicompyler-core` in the executables for the next `DVHA` release.  Source code `DVHA` users will need to manually install the latest `dicompyler-core` master until it's available on PyPI.  This issue affects `dicompyler-core <= 0.5.5`.

`pip install --upgrade git+https://github.com/dicompyler/dicompyler-core.git`
